### PR TITLE
adding cc derivative to options page

### PR DESCRIPTION
**Pull request by bdolor**
Using the guidelines outlined in 'best practices for attribution', minimal functionality (title, author, source, license) has been added for assigning attribution for a derivative work. 

http://wiki.creativecommons.org/Best_practices_for_attribution#This_is_a_good_attribution_for_material_from_which_you_created_a_derivative_work

### CODE REVIEW

**Comment by bdolor** [comment]
10 months since the PR was initiated. What is the status @gnotaras?

**Comment by gnotaras** [comment]
Hi @bdolor, I'm really sorry for not seeing this PR earlier.

Also thanks for implementing and contributing this feature.

Unfortunately, it is impossible to merge at this time, because of 2 problems:

1) The CC-Configurator 1.8.X series has been released, which has different functionality than the 1.5.X. The licenses can now be customized on a per post basis either from the License metabox or programmatically via the available filters. From what I see, this code adds the relevant options to the array of the general plugin settings and also the relevant form elements to the main configuration page of the plugin. According to the new functionality in 1.8.X, the info about the derivative work should be stored in custom fields and the form elements should be available in the License metabox in the post editing screen, so as to be able to add the details about the source work on a per post basis.

2) While developing 1.8.X, adding support for source work attribution puzzled me for a while. If you check the sources, you will notice that the relevant code to support this feature had been written for 1.8.0 ([1](https://bitbucket.org/gnotaras/wordpress-creative-commons-configurator/src/41f6d95ad5f16fc471b9270efbe203082708ad5e/bccl-admin-panel.php?at=default), [2](https://bitbucket.org/gnotaras/wordpress-creative-commons-configurator/src/41f6d95ad5f16fc471b9270efbe203082708ad5e/bccl-admin-panel.php?at=default#cl-778), [3](https://bitbucket.org/gnotaras/wordpress-creative-commons-configurator/src/41f6d95ad5f16fc471b9270efbe203082708ad5e/bccl-generators.php?at=default#cl-286) -- links to repo on bitbucket as I haven't synced it with GitHub yet), but is currently either commented out or not used. The reason it is not used is because I think it rather adds bloat to the License metabox.

Currently, I'm still in the process of trying to decide whether this feature should be added in the metabox or let the user freely write about it in the post. I haven't made up my mind yet, so the code is neither deleted nor used.

Your feedback is welcome and appreciated.

George

**Comment by gnotaras** [comment]
Synced the repositories.

**Comment by gnotaras** [comment]
Brad, I'm going to close this PR. I intend to add a new setting that enables or disables source work attribution (as a metabox feature) as it is currently implemented in 1.8.X.

**Pull request closed without merging**
